USE DATABASE AWS_SNF_CICD;
USE SCHEMA DRAI_CICD;

CREATE OR REPLACE TABLE CLAIMS_DATA_DEPLOY (
    CLAIM_ID NUMBER,
    POLICY_ID NUMBER,
    CUSTOMER_NAME STRING,
    CLAIM_TYPE STRING,
    CLAIM_AMOUNT NUMBER(10,2),
    CLAIM_STATUS STRING,
    CLAIM_DATE DATE
);
